dateModified: 1592273341
email:
  fromEmail: philipp@rppld.co
  fromName: 'Craft CMS Project Starter'
  template: null
  transportSettings: null
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  f63ad89a-254d-4d4b-86c6-d73a3e689519:
    name: Default
fields:
  22e37ada-af96-47e3-aa48-53d0568dfcc1:
    contentColumnType: string
    fieldGroup: f63ad89a-254d-4d4b-86c6-d73a3e689519
    handle: productSingle
    instructions: ''
    name: 'Product Single'
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select a Product'
      source: null
      sources:
        - 'section:376da652-b41f-4adf-9d5d-4b416105bb31'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a09dd241-1432-41cb-bd3e-3c29082d1d90:
    contentColumnType: string
    fieldGroup: f63ad89a-254d-4d4b-86c6-d73a3e689519
    handle: categoryImage
    instructions: ''
    name: 'Category Image'
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:62e59e02-40ad-4e3b-b574-4059ccb41e80'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: 'Add an Image'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:62e59e02-40ad-4e3b-b574-4059ccb41e80'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b31d50e1-4f27-4676-8fdd-afa39b3baa27:
    contentColumnType: string
    fieldGroup: f63ad89a-254d-4d4b-86c6-d73a3e689519
    handle: productList
    instructions: ''
    name: 'Product List'
    searchable: true
    settings:
      limit: ''
      localizeRelations: false
      selectionLabel: 'Add a product'
      source: null
      sources:
        - 'section:376da652-b41f-4adf-9d5d-4b416105bb31'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  dd939d7d-5ef4-4d06-8d9f-8fa1315e0721:
    contentColumnType: text
    fieldGroup: f63ad89a-254d-4d4b-86c6-d73a3e689519
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
plugins:
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
  scss:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
sections:
  376da652-b41f-4adf-9d5d-4b416105bb31:
    enableVersioning: true
    entryTypes:
      3f2cff5c-fba1-422e-ac58-124ae75eeada:
        handle: products
        hasTitleField: true
        name: Products
        sortOrder: 1
        titleFormat: null
        titleLabel: Title
    handle: products
    name: Products
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      aebac91c-fff6-4f09-b5d1-72694fe08a75:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'product/{slug}'
    type: channel
  540d7d7f-a6bb-4d10-a178-9296fdd989d5:
    enableVersioning: true
    entryTypes:
      7f4690cd-0a2d-4e87-8809-f40b3be31ffe:
        fieldLayouts:
          d8ddc405-cd8f-4b50-9b1e-14f08874e114:
            tabs:
              -
                fields:
                  dd939d7d-5ef4-4d06-8d9f-8fa1315e0721:
                    required: false
                    sortOrder: 1
                name: Content
                sortOrder: 1
        handle: homepage
        hasTitleField: false
        name: Homepage
        sortOrder: 1
        titleFormat: '{section.name|raw}'
        titleLabel: null
    handle: homepage
    name: Homepage
    previewTargets:
      -
        label: 'Primary entry page'
        urlFormat: '{url}'
    propagationMethod: all
    siteSettings:
      aebac91c-fff6-4f09-b5d1-72694fe08a75:
        enabledByDefault: true
        hasUrls: true
        template: index
        uriFormat: __home__
    type: single
  6986f39b-427a-40c4-acc9-039d2d07352f:
    enableVersioning: true
    entryTypes:
      1955ffe8-dd87-49cc-95f8-5d17109656de:
        fieldLayouts:
          1d78d3a3-7d5d-4d9c-88a6-7590e93bde77:
            tabs:
              -
                fields:
                  a09dd241-1432-41cb-bd3e-3c29082d1d90:
                    required: false
                    sortOrder: 1
                name: 'Tab 1'
                sortOrder: 1
        handle: productCategories
        hasTitleField: true
        name: 'Product Categories'
        sortOrder: 1
        titleFormat: ''
        titleLabel: Title
      55770925-95b6-4d26-8f5f-0a3077d5dead:
        fieldLayouts:
          611a4230-bd16-4319-9089-2ca1b2cce059:
            tabs:
              -
                fields:
                  22e37ada-af96-47e3-aa48-53d0568dfcc1:
                    required: false
                    sortOrder: 1
                name: 'Tab 1'
                sortOrder: 1
        handle: productSingle
        hasTitleField: true
        name: 'Product Single'
        sortOrder: 3
        titleFormat: ''
        titleLabel: Title
      9d2e3acb-afe7-4b70-a3f0-005d0d8bc680:
        fieldLayouts:
          8e2301aa-e91d-4315-aa15-19847b342687:
            tabs:
              -
                fields:
                  b31d50e1-4f27-4676-8fdd-afa39b3baa27:
                    required: false
                    sortOrder: 1
                name: 'Tab 1'
                sortOrder: 1
        handle: productList
        hasTitleField: true
        name: 'Product List'
        sortOrder: 2
        titleFormat: ''
        titleLabel: Title
    handle: productCategories
    name: 'Product Categories'
    previewTargets:
      -
        __assoc__:
          -
            - label
            - 'Primary entry page'
          -
            - urlFormat
            - '{url}'
          -
            - refresh
            - '1'
    propagationMethod: all
    siteSettings:
      aebac91c-fff6-4f09-b5d1-72694fe08a75:
        enabledByDefault: true
        hasUrls: true
        template: _products/entry
        uriFormat: '{% if parent.parent.parent %}{{ parent.parent.parent.slug }}/{% endif %}/{% if parent.parent %}{{ parent.parent.slug }}/{% endif %}{% if parent %}{{ parent.slug }}/{% endif %}{slug}'
    structure:
      maxLevels: 4
      uid: 45de11af-729e-4e0f-be1c-458bd88f0267
    type: structure
siteGroups:
  a0059ff2-95fa-4b45-9b83-d33adaccc6e4:
    name: Default
sites:
  aebac91c-fff6-4f09-b5d1-72694fe08a75:
    baseUrl: /
    handle: default
    hasUrls: true
    language: en
    name: Ronzoni
    primary: true
    siteGroup: a0059ff2-95fa-4b45-9b83-d33adaccc6e4
    sortOrder: 1
system:
  edition: pro
  live: true
  name: Ronzoni
  schemaVersion: 3.4.10
  timeZone: America/Chicago
users:
  allowPublicRegistration: true
  defaultGroup: 63d1ea93-3888-48b7-9fd1-a1703137728c
  groups:
    63d1ea93-3888-48b7-9fd1-a1703137728c:
      handle: publicUsers
      name: 'Public Users'
      permissions:
        - 'createentries:9aedcdf4-6fc4-4379-82d5-5159b204ea94'
        - 'publishentries:9aedcdf4-6fc4-4379-82d5-5159b204ea94'
        - 'deleteentries:9aedcdf4-6fc4-4379-82d5-5159b204ea94'
        - 'editentries:9aedcdf4-6fc4-4379-82d5-5159b204ea94'
    93873acc-f366-48e4-8150-3355c1fc38b5:
      handle: organizations
      name: Organizations
  photoSubpath: ''
  photoVolumeUid: 62e59e02-40ad-4e3b-b574-4059ccb41e80
  requireEmailVerification: false
volumes:
  62e59e02-40ad-4e3b-b574-4059ccb41e80:
    handle: uploads
    hasUrls: true
    name: Uploads
    settings:
      path: /Users/philipp/Sites/unionhaus/web/uploads
    sortOrder: 1
    type: craft\volumes\Local
    url: 'http://craftcms-webpack-boilerplate.dev//uploads'
